stages:
- name: maven
  steps:
  - runScriptConfig:
      image: maven:3.6.0-jdk-8-alpine
      shellScript: |-
        mvn clean package -pl back-boot -am -Dmaven.test.skip=true
        ls
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 10.4.82.184:31597/sample/back-boot
      pushRemote: true
      registry: 10.4.82.184:31597
timeout: 60
notification: {}
