stages:
- name: npm
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: "cd front-vue\nnpm install \nnpm run build:stage"
- name: maven-docker
  steps:
  - runScriptConfig:
      image: twalter/maven-docker
      shellScript: |-
        cd back-boot
        mvn clean package docker:build -DpushImage
        ls
        ls target
timeout: 60
notification: {}
