stages:
- name: maven
  steps:
  - runScriptConfig:
      image: maven:3.6.0-jdk-8-alpine
      shellScript: |-
        mvn clean package -pl back-boot -am -Dmaven.test.skip=true
        ls
- name: public
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: back-boot
      registry: reg.enncloud.cn
timeout: 60
notification: {}
