stages:
- name: npm
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd front-vue
        npm install --registry http://nexus.enncloud.cn/repository/npm/
        npm run build:stage
timeout: 60
notification: {}
