stages:
- name: npm
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cd front-vue
        npm install --registry http://10.4.82.184:30850/repository/npm-group/
        npm run build:stage
- name: maven
  steps:
  - runScriptConfig:
      image: maven:3.6.0-jdk-8-alpine
      shellScript: |-
        mvn clean package -pl back-boot -am -Dmaven.test.skip=true
        ls
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: reg.enncloud.cn/fnw-dev/back-boot
      pushRemote: true
      registry: reg.enncloud.cn
timeout: 60
notification: {}
